### ISSUE TITLE
Add additional information to the beans

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-backports#17]
I would like to have the following additional information around as I wasn't entirely sure of what I would need or not in the UI. Better include them while we're playing with the GraphQL queries.

**Pull requests**

- [x] description
- [x] merge date
- [x] labels
- [x] current milestone

**Issue**

- [x] description
- [x] author
- [x] URL to the issue

**User**

- [x] first name
- [x] last name

**Comment by gastaldi** [comment]
@gsmet the PR's current milestone is already set in https://github.com/quarkusio/quarkus-backports/blob/master/src/main/java/io/quarkus/backports/model/PullRequest.java#L16, do you mean something different?

**Comment by gsmet** [comment]
Ah no, I simply missed it :). Sorry for the noise!
