### ISSUE TITLE
Assigning milestone doesn't seem to work

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-backports#2]
Removing labels works OK.

But assigning a milestone doesn't seem to work. The API call succeeds (at least there's no exception) but the milestone is not set.

I tried to set it to null and then set it again to another value in case it wouldn't be able to change a milestone but it didn't work either.

**Comment by gastaldi** [comment]
It's a bug in the API and I fixed in https://github.com/hub4j/github-api/pull/899

**Comment by gastaldi** [comment]
Closing as out-of-date
