### ISSUE TITLE
Updating fixed issues

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-backports#5]
Since recently, GitHub has this notion of Linked issues for a PR i.e. issues that will get closed if the PR is closed.

I have no idea if they are exposed in the API but that would be better than having to parse the PR description to find issues.

Fixed issues should see their backport label removed and their milestone assigned.

**Comment by gastaldi** [comment]
This is the solution I found: https://github.community/t/get-all-issues-linked-to-a-pull-request/14653/6

**Comment by gsmet** [comment]
That won't work unfortunately as issues can be linked in the timeline even if they are not fixed by the PR.

The "Linked issues" feature of GitHub is in fact a "Fixed issues" and only display the ones that might be fixed.

If this feature is still not available in the API, I think we will have to parse the description unfortunately.

**Comment by gastaldi** [comment]
> That won't work unfortunately as issues can be linked in the timeline even if they are not fixed by the PR.

Do you have an example? I am not really following.

Every time an issue is linked in the Pull Request timeline a `CONNECTED` event is triggered (which makes the issue show in the "Linked Issues" section), so counting each triggered event is a pretty valid solution IMHO.

**Comment by gsmet** [comment]
What worries me is if someone links the PR somehow without it being to close an issue. There are issues when we have a "see #1345" or PR which contains a "related to "#1234" without the PR closing the issue.

IIRC, in this case, it shows something in the timeline but AFAIK the Linked issues are only the one supposed to be closed by the merge of the PR which is a bit different IMHO.

Except if the event is somehow typed? Also we need to be sure what is in the description triggers events.

**Comment by gastaldi** [comment]
Right, I'll investigate that. Meanwhile can you merge #14 and update the UI to show the linked issues for a PR from the model?
